# Generated by Django 5.1.6 on 2025-03-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ALL', 'all'), ('AGAHAN', 'agahan'), ('TANGHALIAN', 'tanghalian'), ('HAPUNAN', 'hapunan'), ('MERIENDA', 'merienda')], default='ALL', max_length=20),
        ),
    ]
